name: FactionsBridge
main: cc.javajobs.factionsbridge.BridgePlugin
version: 1.2.0
api-version: 1.16
softdepend: [Factions, FactionsX, FactionsBlue, Kingdoms, LegacyFactions, MedievalFactions, UltimateFactions]